### ISSUE TITLE
possible log uploader error, strange zone change message

### ISSUE THREAD

**Issue by petersgriffin** [amckinley/heathskin#22]
Found in b6162a531ee72ddce72f242bf5a999dcd831cb86

in data/game_logs/priest_test_game01.txt, line 11189:

[Zone] `() - id=13 local=False [name=Antique Healbot id=32 zone=HAND zonePos=0 cardId=GVG_069 player=1] zone from FRIENDLY DECK -> FRIENDLY HAND

$ heathskin-replayer --log-style v1 data/game_logs/priest_test_game01.txt --log-debug
...
2015-04-22 11:14:01,389 DEBUG [log_parser.py:70] no parser for line taskListId=75 changeListId=13 taskStart=0 taskEnd=3
      11172
      11173
      11174
      11175
      11176
      11177
      11178
      11179
      11180
2015-04-22 11:14:01,389 INFO [entity.py:57] Updating [Entity entity_id=32] ZONE [FRIENDLY DECK -> FRIENDLY HAND]
      11181
      11182
      11183
      11184
      11185
      11186
      11187
      11188
      11189
2015-04-22 11:14:01,390 ERROR [heathskin-replayer:98] Replayer crashed.
Traceback (most recent call last):
  File "/Users/peterg/GDrive/projects/heathskin/bin/heathskin-replayer", line 93, in main
    replayer(args)
  File "/Users/peterg/GDrive/projects/heathskin/bin/heathskin-replayer", line 136, in replayer
    gs.feed_line(line.rstrip())
  File "/Users/peterg/GDrive/projects/heathskin/heathskin/game_state.py", line 102, in feed_line
    self.parser.feed_line(**results.groupdict())
  File "/Users/peterg/GDrive/projects/heathskin/heathskin/log_parser.py", line 64, in feed_line
    "got unknown log_source {}".format(log_source))
PreventableException: got unknown log_source `()

**Comment by petersgriffin** [comment]
assuming it's a one-off error, going to hand-edit the log file itself and watch for more.
